
## 监听地址和端口
listeners.tcp.local    = 0.0.0.0:5672

loopback_users.guest = false

## 用户名和密码
default_user = guest
default_pass = guest

## 日志相关
log.console = true
log.dir = /usr/local/app/rabbitmq/log/
log.file = rabbit.log
log.file.level = info

heartbeat = 60
handshake_timeout = 10000   # 10秒

##  内存设置
# vm_memory_high_watermark.relative = 0.4
# vm_memory_high_watermark.absolute = 2GB