server {

    # 配置监听
    listen 80;
    server_name example.com;
    root  /www/project/public;
    # 配置日志
    access_log /usr/local/app/nginx/logs/project-nginx-access.log;
    error_log /usr/local/app/nginx/logs/project-error.log;

    # 重写
    location / {
            if (!-f $request_filename) {
                   rewrite  ^(.*)$  /index.php?s=/$1  last;
            }
    }

    location ~ \.php$ {
           fastcgi_pass  jesse-php8.0-service:9000;  ## PHP fpm
           fastcgi_index  index.php;
           fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
           include        fastcgi_params;
    }
}